branches:
  only:
    - master
language: node_js
node_js:
  - stable
before_install:
  - rvm install 2.1.5
  - npm install -g grunt-cli
install:
  - gem install compass
  - pip install --user fpdf
  - npm install
  - npm run bower
script:
  - ./publish-to-gh-pages.sh
after_success:
env:
  global:
    - GitHub_REF: github.com/chaoskyme/resume.git
    - secure: "AD8hwdqZ813Chf71Tb/Tpyszg07WoepvbmO3N8lIzzzIX3hkrVFcmRVQaMgzRIXVBYVRbwZY5zxYImv47hcbC38poetmO8T5n94RzK9Z/eWG8PYlIRLDKboFO+NW8MbcixU6hK0KfUSAX8YMG4F/qzQBff2YUPmGCTtNOK4n/imWwKro73vBNj5nh95FH3AgSolCpyr9m9xoC6gXSRXnvSgHjXQ/F80qMmaOSMZsUNgdUg1iS8wvOvWcr27MGngUAgLtmd9I203Z+td24sgkV9dUJfIUCEqRzpYYCFQMUeu9uSt3xejAj4KoMu1OiS0JgMXaZLiow1QD80Gp7u2mtSeZLcLA/fOOe5hKJ9UQUsv/JvrLCSklor9LSOjPx1WhNvt8S/PULTdC/gMgfm213oq/PAOe4ET8oiy5k3zJcBQkfuI5LwRNMGtJrhlgwZE3C11CGDvKf7M6hEJbRWtS7AhWM4XtyZTNr9La5ovUf22Si5k92hOmVChh9oeEFcXReFR+TRJM4qk9YuDlWbuwDOM5OfNsa+ca0hdfiX4hFdu6XkW7Q63Z15ohAQYqjUAxZ1p1SKsCTDX/ojYC5/XFt9AnkYVIeNCDoUwbSRtLl+ArDgGqOFGPYEpz3JHWOIB3NbKZJCnVzqikaLJDt0tcy8PO2ATA6XYzlYs8rzSV9Kc="
