branches:
  only:
    - master
language: node_js
node_js:
  - stable
before_install:
  - rvm install 2.1.5
  - npm install -g grunt-cli
install:
  - gem install compass
  - pip install --user fpdf
  - npm install
  - npm run bower
script:
  - ./publish-to-gh-pages.sh
after_success:
env:
  global:
    - GitHub_REF: github.com/chaoskyme/resume.git
    - secure: "rjEjV139mSjB5H3/vabs04ReUmjGSi5kC4XYF7ZjZanEuLwpwIEnpwlNFcECLb0HLlSs0uJfPnvUUnf4eP1aDpsrL6MMRddXkCDIHWMP90iED1vEq94U4iTybGg+lvAfXrmCVvRnIuEYEwe41oYag8xBeI0VKfDvLbpf+sTB5O/JtfNao6UTmhAwdKO/SfM6byTpgqjqfSd16Nm/ZQXOYw95SMR9kMqc2Xx8i12Fi9mpvHUMYa/ff3boPF9jm/5nbFFvoo5EhpbKHmLRclR4iqcjma2bqyU5fJxLFs77syHZaA6bO6JjzLvIPy1M2R74ZZx/AgXQaj+xMtVXveMVjuSVcIKVUe0/+IeSyCseLz7GUKB+UgDPK56Yb27alj2t65lf/V4kcPxadL2fWMB3GeHCzdXYtR5uDSnj50tAbItkEMO/O79vzOfMzBVncL4uFe+ZZtqaG7kPz+SDeiuYt59dqzddecIB7IVnNyH3u2UpcBiBBVnnT0lyV3kD8bcZDLXSIiFHBGuV4m8k3O0PZOsI4kSz1jau6+hsfvUHvGd3o3FuCIT4G+uDmHntKtdZXLfvJYOEbzTV+hLPaLrpA7JAjYgPw/GbjOkxqMNO2h3DcFbBvhdqY4RJ6EwY5gNYAsUfgVzINry8/dCg08adygnI+t4eM+Nnt4+nm27o+1o="
