branches:
  only:
    - master
language: node_js
node_js:
  - stable
before_install:
  - rvm install 2.1.5
  - npm install -g grunt-cli
install:
  - gem install compass
  - pip install --user fpdf
  - npm install
  - npm run bower
script:
  - ./publish-to-gh-pages.sh
after_success:
env:
  global:
    - GitHub_REF: github.com/chaoskyme/resume.git
    - secure: "Ikgw+4Vq2YSk+3vMpsReInHf1m5EGQ1gZi8AYsSFJ33pOL8KFjbEqEOvABg7pPpmac/QwffTuV26uK5vnLlLyVYLxWrz5DxyslCnW+rfrhVozksIFd3YEjOn3x4nJLnrP+wzlp1xwJ+M3fcanWRGb4ps0DGd+8OdA+Ae15325LzCEaaJW9WAybKtpeWx986vEmIkmmRxgcsqy7KwMpTEbolq9E88JrgCWYydfogYuBpfK9eOG1d9c9NCdZk6VkVBXXd3R3CoN2JpwPZGC/B7SeAYcz9f6LcaokxtbJj2iNA6s+iCTvHGRaq3y0BPl0F98C0MHEMs1xAbMrKQ/93/3da1sm/4wpg+kJUsMxybrCwdcJR8woQtAYEJH6K1xIAbZBds0J5jJKEJcKCXFh7olytHH7y9i1Ynap3gLaOnoYs/UGsKI0K1JvRikutUM5bmkd8WYztlmxWZlX/MbX4Xy0fGwyLeMEKfcICiCzG2OxTGDwe8n+PbZY+s4Yh35m55WhsI4uWDgw8z5dx5CPgxmvxGpNvLhG76oSeHye96W+8TQQ1ZUZgnztlxUqaQQu1JfNsbLIiQsk38g54iUrehqUS8SXgUvqGCXoHB22wLFXQhuFDSAvx3Omdo6KKRhYl4QWoQ029W4Cm6msxYNEtCPGmVWfG01+5TwM4lgXIhsEA="
